// .trae/skills/annotation/templates/react/AnnotationDot.tsx
import React, { useState, useEffect, useRef, useMemo, useCallback } from 'react'
import { createPortal } from 'react-dom'
import type { AnnotationItem } from './types'
import { registerOnElement, unregisterFromElement } from './annotationRegistry'

interface AnnotationDotProps {
  annotation: AnnotationItem
  index: number
  isActive: boolean
  editMode: boolean
  modalOpen: boolean
  drawerOpen: boolean
  onClick: (id: string) => void
  onMove: (id: string, pos: { x: number; y: number }) => void
}

const MODAL_SELECTORS = [
  '.ant-modal-content', '.el-dialog', '.van-dialog', '.t-dialog', '.n-dialog',
  '[class*="modal-content"]', '[class*="dialog-content"]'
]
const DRAWER_SELECTORS = [
  '.ant-drawer-body', '.el-drawer__body', '.van-popup', '.t-drawer__body',
  '.n-drawer-body-content', '[class*="drawer-body"]', '[class*="drawer-content"]'
]

const categoryMap: Record<string, string> = {
  filter: '筛选', field: '字段', action: '操作', rule: '规则', custom: '自定义'
}

const getFallbackSelectors = (category: string): string[] => {
  if (category === 'filter') return ['[class*="filter"]', '[class*="search"]', 'form:first-of-type']
  if (category === 'action') return ['[class*="action"]', '[class*="toolbar"]', '[class*="operate"]']
  if (category === 'field') return ['[class*="table"]', '[class*="list"]', '[class*="form"]', 'table', 'form']
  if (category === 'rule') return ['[class*="table"]', '[class*="filter"]', 'main']
  return []
}

export function AnnotationDot({ annotation, index, isActive, editMode, modalOpen, drawerOpen, onClick, onMove }: AnnotationDotProps) {
  const [selectorPos, setSelectorPos] = useState<{ x: number; y: number } | null>(null)
  const [isDragging, setIsDragging] = useState(false)
  const [dragPos, setDragPos] = useState<{ x: number; y: number } | null>(null)
  const [showTooltip, setShowTooltip] = useState(false)
  const registeredElRef = useRef<Element | null>(null)
  const hasMovedRef = useRef(false)
  const dragPosRef = useRef<{ x: number; y: number } | null>(null)
  const rafIdRef = useRef<number | null>(null)
  const scheduledRef = useRef(false)

  const container = annotation.container || 'page'
  const isUnplaced = annotation.type === 'position' && annotation.position.x === 0 && annotation.position.y === 0
  const isSelectorPending = annotation.type === 'selector' && selectorPos === null

  const shouldShow = useMemo(() => {
    if (editMode) return true
    if (isUnplaced) return false
    if (isSelectorPending) return false
    if (container === 'page') return !modalOpen && !drawerOpen
    if (container === 'modal') return modalOpen
    if (container === 'drawer') return drawerOpen
    return true
  }, [editMode, isUnplaced, isSelectorPending, container, modalOpen, drawerOpen])

  // Teleport 目标
  const teleportTarget = useMemo(() => {
    const selectors = container === 'modal' ? MODAL_SELECTORS
                    : container === 'drawer' ? DRAWER_SELECTORS
                    : null
    if (!selectors) return null
    for (const sel of selectors) {
      if (document.querySelector(sel)) return document.querySelector(sel) as Element
    }
    return null
  }, [container, modalOpen, drawerOpen])

  const dotColor = annotation.color || '#1677ff'

  // 选择器定位
  const updateSelectorPos = useCallback((): boolean => {
    if (annotation.type !== 'selector') return true

    const computePos = (rect: DOMRect, el: Element) => {
      const stackIndex = registerOnElement(el, annotation.id)
      return { x: rect.left + 2 + stackIndex * 28, y: rect.top + 2 }
    }

    if (annotation.selector) {
      const el = document.querySelector(annotation.selector)
      if (el) {
        const rect = el.getBoundingClientRect()
        if (rect.width === 0 && rect.height === 0) {
          if (registeredElRef.current) { unregisterFromElement(registeredElRef.current, annotation.id); registeredElRef.current = null }
          setSelectorPos(null)
          return false
        }
        if (registeredElRef.current && registeredElRef.current !== el) {
          unregisterFromElement(registeredElRef.current, annotation.id)
        }
        registeredElRef.current = el
        setSelectorPos(computePos(rect, el))
        return true
      }
      if (registeredElRef.current) { unregisterFromElement(registeredElRef.current, annotation.id); registeredElRef.current = null }
      setSelectorPos(null)
      return false
    }

    const fallbacks = getFallbackSelectors(annotation.category)
    for (const sel of fallbacks) {
      const el = document.querySelector(sel)
      if (el) {
        const rect = el.getBoundingClientRect()
        if (rect.width === 0 && rect.height === 0) continue
        if (registeredElRef.current && registeredElRef.current !== el) {
          unregisterFromElement(registeredElRef.current, annotation.id)
        }
        registeredElRef.current = el
        setSelectorPos(computePos(rect, el))
        return true
      }
    }
    if (registeredElRef.current) { unregisterFromElement(registeredElRef.current, annotation.id); registeredElRef.current = null }
    setSelectorPos(null)
    return false
  }, [annotation.type, annotation.selector, annotation.id, annotation.category])

  const scheduleUpdate = useCallback(() => {
    if (scheduledRef.current) return
    scheduledRef.current = true
    requestAnimationFrame(() => { scheduledRef.current = false; updateSelectorPos() })
  }, [updateSelectorPos])

  // 初始定位轮询
  useEffect(() => {
    if (annotation.type !== 'selector') return
    let attempts = 0
    const tick = () => {
      attempts++
      const found = updateSelectorPos()
      if (found || attempts >= 300) { rafIdRef.current = null; return }
      rafIdRef.current = requestAnimationFrame(tick)
    }
    rafIdRef.current = requestAnimationFrame(tick)

    window.addEventListener('scroll', scheduleUpdate, { passive: true, capture: true })
    window.addEventListener('resize', scheduleUpdate, { passive: true })

    const mo = new MutationObserver(scheduleUpdate)
    mo.observe(document.body, { childList: true, subtree: true, attributes: true, attributeFilter: ['style', 'class', 'hidden'] })

    return () => {
      if (rafIdRef.current !== null) cancelAnimationFrame(rafIdRef.current)
      window.removeEventListener('scroll', scheduleUpdate, { capture: true } as any)
      window.removeEventListener('resize', scheduleUpdate)
      mo.disconnect()
      if (registeredElRef.current) unregisterFromElement(registeredElRef.current, annotation.id)
    }
  }, [annotation.type, annotation.selector, annotation.id, updateSelectorPos, scheduleUpdate])

  // 容器状态变化时重新定位
  useEffect(() => {
    setSelectorPos(null)
    if (annotation.type === 'selector') {
      setTimeout(() => updateSelectorPos(), 50)
    }
  }, [modalOpen, drawerOpen, annotation.container])

  // 拖拽
  const handleDragStart = (e: React.MouseEvent) => {
    if (!editMode) return
    const startX = e.clientX
    const startY = e.clientY
    hasMovedRef.current = false
    dragPosRef.current = null

    const onMouseMove = (ev: MouseEvent) => {
      if (!hasMovedRef.current && (Math.abs(ev.clientX - startX) > 3 || Math.abs(ev.clientY - startY) > 3)) {
        setIsDragging(true)
        hasMovedRef.current = true
      }
      if (hasMovedRef.current) {
        const pos = { x: ev.clientX, y: ev.clientY }
        dragPosRef.current = pos
        setDragPos(pos)
      }
    }
    const onMouseUp = () => {
      document.removeEventListener('mousemove', onMouseMove)
      document.removeEventListener('mouseup', onMouseUp)
      if (hasMovedRef.current && dragPosRef.current) onMove(annotation.id, dragPosRef.current)
      setIsDragging(false)
      setDragPos(null)
      dragPosRef.current = null
    }
    document.addEventListener('mousemove', onMouseMove)
    document.addEventListener('mouseup', onMouseUp)
  }

  const handleClick = () => { if (!hasMovedRef.current) onClick(annotation.id) }

  // 位置样式
  const dotStyle = useMemo((): React.CSSProperties => {
    const isInContainer = container !== 'page'
    if (dragPos) return { position: 'fixed', left: dragPos.x - 13, top: dragPos.y - 13, zIndex: 9999, transition: 'none' }
    if (annotation.type === 'selector' && selectorPos) {
      return { position: 'fixed', left: selectorPos.x, top: selectorPos.y, zIndex: isInContainer ? 1100 : 9990 }
    }
    return { position: 'fixed', left: annotation.position.x - 13, top: annotation.position.y - 13, zIndex: isInContainer ? 1100 : 9990 }
  }, [dragPos, annotation.type, selectorPos, annotation.position, container])

  if (!shouldShow) return null

  const className = [
    'annotation-dot',
    isActive && 'annotation-dot-active',
    editMode && 'annotation-dot-edit',
    isDragging && 'annotation-dot-dragging',
    isUnplaced && 'annotation-dot-unplaced',
  ].filter(Boolean).join(' ')

  const dot = (
    <div
      className={className}
      data-annot-id={annotation.id}
      style={{ ...dotStyle, '--dot-color': dotColor } as React.CSSProperties}
      onClick={handleClick}
      onMouseDown={handleDragStart}
      onMouseEnter={() => setShowTooltip(true)}
      onMouseLeave={() => setShowTooltip(false)}
    >
      <span className="dot-number">{index + 1}</span>
      {showTooltip && !isActive && (
        <div className="dot-tooltip">
          <div className="tooltip-title">{annotation.title}</div>
          <div className="tooltip-category">{categoryMap[annotation.category] || annotation.category}</div>
        </div>
      )}
    </div>
  )

  if (teleportTarget) return createPortal(dot, teleportTarget)
  return dot
}

// .windsurf/skills/annotation/templates/vue/AnnotationDot.vue
<!-- 标注圆点：显示在页面上的编号标记，支持 page/modal/drawer 三种宿主容器 -->
<template>
  <!-- 根据 container 决定渲染到哪个容器 -->
  <Teleport :to="teleportTarget" :disabled="!teleportTarget">
    <!-- position 类型且坐标为 (0,0) 时隐藏，等用户在编辑模式下拖放定位 -->
    <div
      v-if="shouldShow"
      class="annotation-dot"
      :class="{
        'annotation-dot-active': isActive,
        'annotation-dot-edit': editMode,
        'annotation-dot-dragging': isDragging,
        'annotation-dot-unplaced': isUnplaced
      }"
      :style="{ ...dotStyle, '--dot-color': dotColor }"
      @click.stop="handleClick"
      @mousedown.stop="handleDragStart"
      @mouseenter="showTooltip = true"
      @mouseleave="showTooltip = false"
    >
      <span class="dot-number">{{ index + 1 }}</span>

      <!-- hover 摘要气泡 -->
      <div v-if="showTooltip && !isActive" class="dot-tooltip">
        <div class="tooltip-title">{{ annotation.title }}</div>
        <div class="tooltip-category">{{ categoryLabel }}</div>
      </div>
    </div>
  </Teleport>
</template>

<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted, nextTick } from 'vue'
import type { AnnotationItem } from './types'

const props = defineProps<{
  annotation: AnnotationItem
  index: number
  isActive: boolean
  editMode: boolean
  /** 当前是否有弹窗/抽屉打开（由父组件传入） */
  modalOpen: boolean
  drawerOpen: boolean
}>()

const emit = defineEmits<{
  click: [id: string]
  move: [id: string, pos: { x: number; y: number }]
}>()

// 宿主容器，默认 page
const container = computed(() => props.annotation.container || 'page')

// 是否为未定位的 position 标注
const isUnplaced = computed(() =>
  props.annotation.type === 'position' &&
  props.annotation.position.x === 0 &&
  props.annotation.position.y === 0
)

/**
 * 决定是否显示：
 * - page 容器：弹窗或抽屉打开时隐藏（避免遮挡）
 * - modal 容器：只有弹窗打开时才显示
 * - drawer 容器：只有抽屉打开时才显示
 * - 编辑模式下始终显示（方便调整位置）
 */
const shouldShow = computed(() => {
  if (props.editMode) return true
  if (isUnplaced.value) return false

  if (container.value === 'page') {
    // 页面标注：弹窗或抽屉打开时隐藏
    return !props.modalOpen && !props.drawerOpen
  }
  if (container.value === 'modal') {
    // 弹窗标注：只有弹窗打开时显示
    return props.modalOpen
  }
  if (container.value === 'drawer') {
    // 抽屉标注：只有抽屉打开时显示
    return props.drawerOpen
  }
  return true
})

/**
 * Teleport 目标：
 * - page → 不 teleport（disabled），渲染在 overlay 内
 * - modal → teleport 到 .ant-modal-wrap（弹窗容器）
 * - drawer → teleport 到 .ant-drawer-body（抽屉内容区）
 *
 * 目标容器不存在时返回 null，Teleport disabled，标注点不渲染
 */
const teleportTarget = computed<string | null>(() => {
  if (container.value === 'modal') {
    return document.querySelector('.ant-modal-wrap') ? '.ant-modal-wrap' : null
  }
  if (container.value === 'drawer') {
    return document.querySelector('.ant-drawer-body') ? '.ant-drawer-body' : null
  }
  return null  // page 容器不需要 teleport
})

const isDragging = ref(false)
let hasMoved = false
const dragPos = ref<{ x: number; y: number } | null>(null)

// 编辑模式下拖拽移动
const handleDragStart = (e: MouseEvent) => {
  if (!props.editMode) return
  const startX = e.clientX
  const startY = e.clientY
  hasMoved = false

  const onMove = (ev: MouseEvent) => {
    if (!hasMoved && (Math.abs(ev.clientX - startX) > 3 || Math.abs(ev.clientY - startY) > 3)) {
      isDragging.value = true
      hasMoved = true
    }
    if (hasMoved) {
      dragPos.value = { x: ev.clientX, y: ev.clientY }
    }
  }
  const onUp = () => {
    document.removeEventListener('mousemove', onMove)
    document.removeEventListener('mouseup', onUp)
    if (hasMoved && dragPos.value) {
      emit('move', props.annotation.id, { x: dragPos.value.x, y: dragPos.value.y })
    }
    isDragging.value = false
    dragPos.value = null
  }
  document.addEventListener('mousemove', onMove)
  document.addEventListener('mouseup', onUp)
}

const handleClick = () => {
  if (!hasMoved) emit('click', props.annotation.id)
}

const showTooltip = ref(false)

const dotColor = computed(() => props.annotation.color || '#1677ff')

const categoryMap: Record<string, string> = {
  filter: '筛选', field: '字段', action: '操作', rule: '规则', custom: '自定义'
}
const categoryLabel = computed(() => categoryMap[props.annotation.category] || props.annotation.category)

// 选择器定位：找到元素后取其屏幕坐标
const selectorPos = ref<{ x: number; y: number } | null>(null)

/**
 * 根据 category 和 title 动态推断候选选择器列表
 * 当 selector 字段找不到元素时作为降级方案
 */
const getFallbackSelectors = (): string[] => {
  const { category, title } = props.annotation
  const t = title.toLowerCase()

  if (category === 'filter') {
    return [
      '[class*="filter-card"]', '[class*="filter_card"]',
      '[class*="search-card"]', '[class*="search_card"]',
      '[class*="filter-form"]', '[class*="search-form"]',
      '.el-form:first-of-type', 'form:first-of-type'
    ]
  }

  if (category === 'action') {
    return [
      '[class*="action-bar"]', '[class*="action_bar"]',
      '[class*="toolbar"]', '[class*="tool-bar"]',
      '[class*="btn-bar"]', '[class*="operate"]',
      '[class*="header-btn"]'
    ]
  }

  if (category === 'field') {
    if (t.includes('列表') || t.includes('表格') || t.includes('list')) {
      return [
        '.ant-table', '.el-table', 'table',
        '[class*="table-card"]', '[class*="table_card"]'
      ]
    }
    if (t.includes('表单') || t.includes('form')) {
      return [
        '.ant-form', '.el-form', 'form',
        '[class*="form-card"]', '[class*="form_card"]'
      ]
    }
    if (t.includes('详情') || t.includes('detail') || t.includes('描述')) {
      return [
        '.ant-descriptions', '.el-descriptions',
        '[class*="detail"]', '[class*="info-card"]'
      ]
    }
    if (t.includes('步骤') || t.includes('step')) {
      return [
        '.ant-steps', '.el-steps',
        '[class*="form-steps"]', '[class*="step"]'
      ]
    }
    if (t.includes('折叠') || t.includes('collapse') || t.includes('记录')) {
      return ['.ant-collapse', '.el-collapse', '[class*="collapse"]']
    }
    if (t.includes('时间轴') || t.includes('timeline') || t.includes('流转')) {
      return ['.ant-timeline', '.el-timeline', '[class*="timeline"]']
    }
    // 通用字段：找表格或描述列表
    return ['.ant-table', '.el-table', '.ant-descriptions', '.el-descriptions']
  }

  if (category === 'rule') {
    // 规则标注：就近挂在操作栏或表格上
    return [
      '[class*="action-bar"]', '[class*="toolbar"]',
      '.ant-table', '.el-table',
      '[class*="filter-card"]'
    ]
  }

  return []
}

/**
 * 查找元素：先用 selector，找不到再用 category+title 动态推断
 * 找不到时保持上次位置（不消失，不报错）
 */
const updateSelectorPos = () => {
  if (props.annotation.type !== 'selector') return

  // 第一步：直接用 selector 查
  if (props.annotation.selector) {
    const el = document.querySelector(props.annotation.selector)
    if (el) {
      const rect = el.getBoundingClientRect()
      selectorPos.value = { x: rect.left + 8, y: rect.top + 8 }
      return
    }
  }

  // 第二步：selector 找不到，根据 category + title 动态推断
  const fallbacks = getFallbackSelectors()
  for (const sel of fallbacks) {
    const el = document.querySelector(sel)
    if (el) {
      const rect = el.getBoundingClientRect()
      // 偏移量：每个标注点错开，避免完全重叠
      const offset = (props.index % 4) * 20
      selectorPos.value = { x: rect.left + 8 + offset, y: rect.top + 8 + offset }
      return
    }
  }

  // 两步都找不到：保持上次位置，不置 null（避免标注点消失）
  // selectorPos 保持原值
}

/**
 * 计算圆点位置
 * - page 容器：fixed 定位，相对视口
 * - modal/drawer 容器：absolute 定位，相对 teleport 目标容器
 *   容器本身是 fixed/absolute 的，所以坐标仍用视口坐标减去容器偏移
 */
const dotStyle = computed(() => {
  const isInContainer = container.value !== 'page'

  // 拖拽中：跟随鼠标（始终用 fixed）
  if (dragPos.value) {
    return {
      position: 'fixed' as const,
      left: `${dragPos.value.x - 13}px`,
      top: `${dragPos.value.y - 13}px`,
      zIndex: 9999,
      transition: 'none'
    }
  }

  // 选择器定位
  if (props.annotation.type === 'selector' && selectorPos.value) {
    if (isInContainer) {
      // teleport 到容器内：用 fixed 定位，z-index 高于弹窗内容但低于弹窗遮罩
      return {
        position: 'fixed' as const,
        left: `${selectorPos.value.x - 13}px`,
        top: `${selectorPos.value.y - 13}px`,
        zIndex: 1100  // 高于 ant-modal(1000) 但合理
      }
    }
    return {
      position: 'fixed' as const,
      left: `${selectorPos.value.x - 13}px`,
      top: `${selectorPos.value.y - 13}px`,
      zIndex: 9990
    }
  }

  // 手动标注（position 类型）
  const z = isInContainer ? 1100 : 9990
  return {
    position: 'fixed' as const,
    left: `${props.annotation.position.x - 13}px`,
    top: `${props.annotation.position.y - 13}px`,
    zIndex: z
  }
})

let rafId: number | null = null

const startPositionTracking = () => {
  if (props.annotation.type !== 'selector') return
  const tick = () => {
    updateSelectorPos()
    rafId = requestAnimationFrame(tick)
  }
  rafId = requestAnimationFrame(tick)
}

const stopPositionTracking = () => {
  if (rafId !== null) {
    cancelAnimationFrame(rafId)
    rafId = null
  }
}

onMounted(() => {
  nextTick(() => {
    updateSelectorPos()
    startPositionTracking()
  })
  window.addEventListener('scroll', updateSelectorPos, { passive: true })
  window.addEventListener('resize', updateSelectorPos, { passive: true })
})

onUnmounted(() => {
  stopPositionTracking()
  window.removeEventListener('scroll', updateSelectorPos)
  window.removeEventListener('resize', updateSelectorPos)
})
</script>

<style scoped lang="scss">
.annotation-dot {
  width: 26px;
  height: 26px;
  border-radius: 50%;
  background: var(--dot-color, #1677ff);
  color: #fff;
  display: flex;
  align-items: center;
  justify-content: center;
  cursor: pointer;
  box-shadow: 0 2px 8px color-mix(in srgb, var(--dot-color, #1677ff) 50%, transparent);
  transition: transform 0.15s, box-shadow 0.15s;
  user-select: none;
  pointer-events: auto;
  border: 2px solid rgba(255, 255, 255, 0.6);
}

.annotation-dot:hover {
  transform: scale(1.2);
  box-shadow: 0 4px 14px color-mix(in srgb, var(--dot-color, #1677ff) 60%, transparent);
}

.annotation-dot-active {
  --dot-color: #ff4d4f;
  transform: scale(1.1);
}

.annotation-dot-edit {
  cursor: grab;
}

/* 未定位的 position 标注：编辑模式下固定显示在右下角，虚线边框提示需要拖放 */
.annotation-dot-unplaced {
  position: fixed !important;
  bottom: 80px;
  right: 24px;
  left: auto !important;
  top: auto !important;
  border: 2px dashed rgba(255, 255, 255, 0.8) !important;
  opacity: 0.85;
}

.annotation-dot-dragging {
  cursor: grabbing;
  transform: scale(1.15);
}

.dot-number {
  font-size: 11px;
  font-weight: 700;
  line-height: 1;
}

.dot-tooltip {
  position: fixed;
  top: -8px;
  left: calc(100% + 8px);
  background: rgba(0, 0, 0, 0.8);
  color: #fff;
  padding: 6px 10px;
  border-radius: 6px;
  white-space: nowrap;
  font-size: 12px;
  pointer-events: none;
  z-index: 9999;
}

.tooltip-title {
  font-weight: 500;
  margin-bottom: 2px;
}

.tooltip-category {
  font-size: 11px;
  color: rgba(255, 255, 255, 0.7);
}
</style>
